stages:
  - build

.plaftorms_template: &platforms_definition
  only:
    - branches
    - master # I suppose that we can work directly on master
    - merge_request

make_dyssol:
  <<: *platforms_definition
  stage: build
  image: debian:bullseye
  script:
    - apt-get update && apt-get install -y cmake build-essential libsundials-dev libhdf5-serial-dev libqglviewer-dev-qt5
    - mkdir build && cd build && cmake .. && make
