stages:
  - build

.plaftorms_template: &platforms_definition
  only:
    - branches
    - master # I suppose that we can work directly on master
    - merge_request
  stage: build
  script:
    - apt-get update && apt-get install -y cmake build-essential libsundials-dev libhdf5-serial-dev libqglviewer-dev-qt5
    - mkdir build && cd build && cmake .. && make

make_bullseye:
  <<: *platforms_definition
  image: debian:bullseye

make_focal:
  <<: *platforms_definition
  image: ubuntu:focal

variables:
  DEBIAN_FRONTEND=noninteractive
