stages:
  - build

.plaftorms_template: &platforms_definition
  only:
    - branches
    - master # I suppose that we can work directly on master
    - merge_request
  stage: build
  script:
    - apt-get update && apt-get install -y cmake ccache build-essential libsundials-dev libhdf5-serial-dev libqt5opengl5-dev
    - export PATH="/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - ccache -s
    - mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_VERBOSE_MAKEFILE=ON  .. && make
    - ccache -s

make_sid:
  <<: *platforms_definition
  image: debian:experimental
  before_script:
    - apt-get update && apt-get install -y libsundials-dev experimental

make_focal:
  <<: *platforms_definition
  image: ubuntu:focal
  before_script:
    - apt-get update && apt-get install -y software-properties-common
    - add-apt-repository ppa:gladky-anton/sundials && apt-get update

make_sid-clang:
  <<: *platforms_definition
  image: debian:experimental
  before_script:
    - apt-get update && apt-get install -y libsundials-dev experimental
    - apt-get install -y clang-11
    - export CC=/usr/bin/clang-11
    - export CXX=/usr/bin/clang++-11

variables:
  DEBIAN_FRONTEND: "noninteractive"

cache:
  paths:
    - ccache
