stages:
  - build

.plaftorms_template: &platforms_definition
  only:
    - branches
    - master # I suppose that we can work directly on master
    - merge_request
  stage: build
  script:
    - apt-get update && apt-get install -y cmake ccache build-essential libsundials-dev libhdf5-serial-dev libqglviewer-dev-qt5
    - export PATH="/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - ccache -s
    - mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_VERBOSE_MAKEFILE=ON  .. && make
    - ccache -s

make_bullseye:
  <<: *platforms_definition
  image: debian:bullseye

make_hirsute:
  <<: *platforms_definition
  image: ubuntu:hirsute

variables:
  DEBIAN_FRONTEND: "noninteractive"

cache:
  paths:
    - ccache
