# paths to files
$inputFilePath  = $args[0]
$outputFilePath = $args[1]

# read the list of units from the input file
$units = Get-Content -Path $inputFilePath | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }

# initialize the output content
$outputContent = @()
# add comments
$outputContent +=  "; This file was generated by the Installer project."
$outputContent +=  "; All manual changes will be reverted after the next project build."
# add header
$outputContent += "#dim UnitsDll[$($units.Count)]"
# iterate through units
for ($i = 0; $i -lt $units.Count; $i++) {
    $outputContent += "#define UnitsDll[$i] `"$($units[$i])`""
}
# add footer
$outputContent += "#define I"

# write the content to the output file
Set-Content -Path $outputFilePath -Value $outputContent -Encoding UTF8

Write-Host $outputFilePath " file generated successfully!"
